// GENERATED from cidade-completa.glb by a one-off offline raycast probe.
// One bit per 2 m cell of the city: 1 = open ground with headroom above,
// 0 = building, prop or outside the map. Spawning, traffic, pedestrian routing
// and the minimap all read this instead of raycasting the city at runtime.
export const CITY_GRID = {
  minX: -72,
  minZ: -112,
  step: 2,
  cols: 91,
  rows: 125,
  /** Mean street height; the city sits essentially flat at this level. */
  groundY: 0.075,
  /** 2723 open cells of 11375, base64 of a little-endian bitmask. */
  bits:
    "AAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAMABAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAADgAAAAAA" +
    "AAAAAAD8AAAAAAAAAAAAAPAGAAAAAAAAAAAA4H0AAAAAAAAAAACA/wcAAAAAAAAAAADvNwAAAAAAADAAAPz/AwAAAAAAwAAA" +
    "+PsfAAAAAAAAAgDwv/8BAAAAAAAAAMD/fx8AAAAAAAAAgN/f/wAAAAAAAAAAfv/7DwAAAAAAAAD8/v//AAAAAAAAAPD7//8H" +
    "AAAAAAAAwP///38AAAAAAAAA///+/wcAAAAAAAD9//3/PwAAAAAAAPj/9v//AwAAAAAAoP////8/AAAAAAAA//////8BAAAA" +
    "AAD4/////x8AAAAAAOD/////3wEAAAAAAP//////DwAAAAAA/P//////AAAAAABg//////8HAAAAAID//////z8AAAAAAPz/" +
    "/////wEAAAAA4P///z//DwAAAACA//////5/AAAAAAD8/////f8DAAAAAuCG//+z/x8AAAAAAP///8///wAAAAAA+P///9//" +
    "BwAAAADA/////v8/AAAAAAD////z//8BAAAAAPj//9/9/w8AAAAAwP//f37/fwAAAAAA/v//////AwAAAADwgf9f//8fAAAA" +
    "AID/+/++//8AAAAAAPzf//f//xcAAAAA4P/+v///PwAAAAwA//f//f//AQAAAAD4v/8f/v8PAAAAAMD//3/f/38AAAAAAP7/" +
    "//v+/wMAAAAA8P//3/f/HwAAAACA//v/vv//AAAAAAD8///3/f8HAAAAAOD////f/z8AAAAAAP///33+/wEAAAAA+P//7/P/" +
    "DwAAAADA//9/n/9/AAAAAAD+///7/v8DAAAAAPD//9/3fx8AAAAAoB/8////+wAAAAAAfN/////fBwAAAADg+/7///8+AAAA" +
    "AADf9/////8BAAAAAPi+/////w8AAAAAwPf9////fwAAAAAAHuD/B/z/AwAAAADw//////8fAAAAAID///////8AAAAAAPz/" +
    "/////wcAAAAA4P//////PwAAAAAA////////AQAAAAD4//////8PAAAABMD/AQD/AQAAAAAgAAAAAAAAAAAAAAABAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAwAAAAAAgAAAAAAMAAAAAAAABAAAADAAAAAAAAAgAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAACAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAA",
} as const;
